/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accounting.client.gui;

import com.accounting.client.gui.models.CurrencyComboBoxModel;
import com.accounting.client.gui.models.DocumentComboBoxModel;
import com.accounting.client.gui.models.EmployeeComboBoxModel;
import com.accounting.client.gui.models.ProductGroupComboBoxModel;
import com.accounting.client.gui.models.ProductUnitComboBoxModel;
import com.accounting.client.utils.NotSupportedServicesException;
import com.accounting.client.utils.RemoteServicesProvider;
import com.accounting.client.utils.WindowsFactory;
import com.accounting.interfaces.IProductsServices;

import java.awt.Window;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author vasiliy
 */
public class ProductAdditionMaster extends javax.swing.JPanel {
    
    /**
     * Creates new form ProductAdditionMaster
     */
    public ProductAdditionMaster() {
        initComponents();
        
        jComboBoxCurrency.setModel(new CurrencyComboBoxModel());
        ((CurrencyComboBoxModel)jComboBoxCurrency.getModel()).update();
        
        jComboBoxDocument.setModel(new DocumentComboBoxModel());
        ((DocumentComboBoxModel)jComboBoxDocument.getModel()).update();
        
        jComboBoxEmployee.setModel(new EmployeeComboBoxModel());
        ((EmployeeComboBoxModel)jComboBoxEmployee.getModel()).update();
        
        jComboBoxGroup.setModel(new ProductGroupComboBoxModel());
        ((ProductGroupComboBoxModel)jComboBoxGroup.getModel()).update();
        
        jComboBoxUnit.setModel(new ProductUnitComboBoxModel());
        ((ProductUnitComboBoxModel)jComboBoxUnit.getModel()).update();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jComboBoxUnit = new javax.swing.JComboBox();
        jComboBoxCurrency = new javax.swing.JComboBox();
        jComboBoxGroup = new javax.swing.JComboBox();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEmployee = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDocument = new javax.swing.JComboBox();
        jButtonAddProductUnit = new javax.swing.JButton();
        jButtonAddCurrency = new javax.swing.JButton();
        jButtonAddProductGroup = new javax.swing.JButton();
        jButtonAddEmployee = new javax.swing.JButton();
        jButtonAddDocument = new javax.swing.JButton();

        jLabel1.setText("Наименование:");

        jLabel2.setText("Количество:");

        jLabel3.setText("Стоимость всех N единиц:");

        jLabel4.setText("Единица измерения:");

        jLabel5.setText("Валюта:");

        jLabel6.setText("Группа:");

        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduct(evt);
            }
        });

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeWindow(evt);
            }
        });

        jLabel7.setText("Сотрудник:");

        jLabel8.setText("Документ:");

        jButtonAddProductUnit.setText("Ещё");
        jButtonAddProductUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductUnit(evt);
            }
        });

        jButtonAddCurrency.setText("Ещё");
        jButtonAddCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCurrency(evt);
            }
        });

        jButtonAddProductGroup.setText("Ещё");
        jButtonAddProductGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductGroup(evt);
            }
        });

        jButtonAddEmployee.setText("Ещё");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployee(evt);
            }
        });

        jButtonAddDocument.setText("Ещё");
        jButtonAddDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDocument(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUnit, 0, 335, Short.MAX_VALUE)
                            .addComponent(jComboBoxCurrency, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGroup, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEmployee, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDocument, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddDocument, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddEmployee, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddProductGroup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddCurrency, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddProductUnit, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAmount)
                            .addComponent(jTextFieldName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrice)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddProductUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddProductGroup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddDocument))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addProduct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduct
        IProductsServices productsServices = null;
        try{
            productsServices = RemoteServicesProvider.getInstance().<IProductsServices>getServices(IProductsServices.class);
        }catch(NotSupportedServicesException e){
            throw new RuntimeException(e);
        }
        
        if(null != productsServices){
            Double amount = Double.parseDouble(jTextFieldAmount.getText());
            productsServices.addProduct(
                    jTextFieldName.getText(),
                    amount,
                    (new BigDecimal(jTextFieldPrice.getText())).divide(new BigDecimal(amount), 5, RoundingMode.HALF_DOWN),
                    ((ProductGroupComboBoxModel)jComboBoxGroup.getModel()).getSelectedItem().Id,
                    ((CurrencyComboBoxModel)jComboBoxCurrency.getModel()).getSelectedItem().Id,
                    ((ProductUnitComboBoxModel)jComboBoxUnit.getModel()).getSelectedItem().Id,
                    ((DocumentComboBoxModel)jComboBoxDocument.getModel()).getSelectedItem().Id,
                    ((EmployeeComboBoxModel)jComboBoxEmployee.getModel()).getSelectedItem().Id
            );
        }else{
            System.err.println("NullPointerException");
        }
        ((Window)this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_addProduct

    private void closeWindow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeWindow
        ((Window)this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_closeWindow

    private void addProductUnit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductUnit
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new ProductUnitAdditionMaster(), "Добавление единицы измерения");
        ((ProductUnitComboBoxModel)jComboBoxUnit.getModel()).update();
    }//GEN-LAST:event_addProductUnit

    private void addCurrency(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCurrency
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new CurrencyAdditionMaster(), "Добавление валюты");
        ((CurrencyComboBoxModel)jComboBoxCurrency.getModel()).update();
    }//GEN-LAST:event_addCurrency

    private void addProductGroup(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductGroup
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new ProductGroupAdditionMaster(), "Добавление группы продуктов");
        ((ProductGroupComboBoxModel)jComboBoxGroup.getModel()).update();
    }//GEN-LAST:event_addProductGroup

    private void addEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployee
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new EmployeeAdditionMaster(), "Добавление сотрудника");
        ((EmployeeComboBoxModel)jComboBoxEmployee.getModel()).update();
    }//GEN-LAST:event_addEmployee

    private void addDocument(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDocument
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new DocumentAdditionMaster(), "Добавление документа");
        ((DocumentComboBoxModel)jComboBoxDocument.getModel()).update();
    }//GEN-LAST:event_addDocument


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddCurrency;
    private javax.swing.JButton jButtonAddDocument;
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonAddProductGroup;
    private javax.swing.JButton jButtonAddProductUnit;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxCurrency;
    private javax.swing.JComboBox jComboBoxDocument;
    private javax.swing.JComboBox jComboBoxEmployee;
    private javax.swing.JComboBox jComboBoxGroup;
    private javax.swing.JComboBox jComboBoxUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
