/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accounting.client.gui;

import com.accounting.client.gui.models.DestinationComboBoxModel;
import com.accounting.client.gui.models.DocumentComboBoxModel;
import com.accounting.client.gui.models.EmployeeComboBoxModel;
import com.accounting.client.utils.NotSupportedServicesException;
import com.accounting.client.utils.RemoteServicesProvider;
import com.accounting.client.utils.WindowsFactory;
import com.accounting.interfaces.IProductsServices;
import com.accounting.models.Product;
import java.awt.Window;

/**
 *
 * @author vasiliy
 */
public class ProductConsumingMaster extends javax.swing.JPanel {
    
    /**
     * Creates new form ProductConsumingMaster
     */
    private Product product;
    
    public ProductConsumingMaster(int productId) {
        initComponents();
        
        try{
            IProductsServices productsServices = RemoteServicesProvider.getInstance().<IProductsServices>getServices(IProductsServices.class);
            this.product = productsServices.getProductById(productId);
        }
        catch(NotSupportedServicesException e){
            throw new RuntimeException(e);
        }
        
        jTextFieldProductName.setText(product.Name);
        
        jComboBoxDocument.setModel(new DocumentComboBoxModel());
        ((DocumentComboBoxModel)jComboBoxDocument.getModel()).update();
        
        jComboBoxEmployee.setModel(new EmployeeComboBoxModel());
        ((EmployeeComboBoxModel)jComboBoxEmployee.getModel()).update();
        
        jComboBoxDestination.setModel(new DestinationComboBoxModel());
        ((DestinationComboBoxModel)jComboBoxDestination.getModel()).update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDocument = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDestination = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxEmployee = new javax.swing.JComboBox();
        jButtonAddDocument = new javax.swing.JButton();
        jButtonAddDestination = new javax.swing.JButton();
        jButtonAddEmployee = new javax.swing.JButton();

        jButton1.setText("Расходовать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumeProduct(evt);
            }
        });

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeWindow(evt);
            }
        });

        jLabel1.setText("Название:");

        jTextFieldProductName.setEditable(false);

        jLabel2.setText("Количество:");

        jLabel3.setText("Документ:");

        jLabel4.setText("Место назначения:");

        jLabel5.setText("Сотрудник:");

        jButtonAddDocument.setText("Ещё");
        jButtonAddDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDocument(evt);
            }
        });

        jButtonAddDestination.setText("Ещё");
        jButtonAddDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDestination(evt);
            }
        });

        jButtonAddEmployee.setText("Ещё");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployee(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxDocument, 0, 285, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAddEmployee, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAddDestination, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAddDocument, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jTextFieldAmount)
                            .addComponent(jTextFieldProductName)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddDocument))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddDestination))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeWindow
        ((Window) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_closeWindow

    private void consumeProduct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumeProduct
        IProductsServices productsServices = null;
        try{
            productsServices = RemoteServicesProvider.getInstance().<IProductsServices>getServices(IProductsServices.class);
        }
        catch(NotSupportedServicesException e){
            throw new RuntimeException(e);
        }
        
        if(null != productsServices){
            productsServices.consumeProduct(
                    product.Id,
                    Double.valueOf(jTextFieldAmount.getText()),
                    ((DocumentComboBoxModel) jComboBoxDocument.getModel()).getSelectedItem().Id,
                    ((DestinationComboBoxModel) jComboBoxDestination.getModel()).getSelectedItem().Id,
                    ((EmployeeComboBoxModel) jComboBoxEmployee.getModel()).getSelectedItem().Id
            );
        }
        ((Window) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_consumeProduct

    private void addEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployee
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new EmployeeAdditionMaster(), "Добавление сотрудника");
        ((EmployeeComboBoxModel)jComboBoxEmployee.getModel()).update();
    }//GEN-LAST:event_addEmployee

    private void addDestination(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDestination
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new DestinationAdditionMaster(), "Добавление места");
        ((DestinationComboBoxModel)jComboBoxDestination.getModel()).update();
    }//GEN-LAST:event_addDestination

    private void addDocument(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDocument
        WindowsFactory.createDialog((Window)this.getTopLevelAncestor(), new DocumentAdditionMaster(), "Добавление документа");
        ((DocumentComboBoxModel)jComboBoxDocument.getModel()).update();
    }//GEN-LAST:event_addDocument


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddDestination;
    private javax.swing.JButton jButtonAddDocument;
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxDestination;
    private javax.swing.JComboBox jComboBoxDocument;
    private javax.swing.JComboBox jComboBoxEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldProductName;
    // End of variables declaration//GEN-END:variables
}
