/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounting.GUI;

import accounting.Interfaces.IProductsManager;
import accounting.Models.Product;
import accounting.PostgreManagers.PostgreModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vasiliy
 */
public class Main extends javax.swing.JPanel {
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        PostgreModule psm = new PostgreModule();
        Injector injector = Guice.createInjector(psm);
        IProductsManager productsManager = injector.getInstance(IProductsManager.class);
       
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(
                new String[]{"Id","Name","Amount","Price","ProductGroupId","CurrencyId","ProductUnitId"}
        );
        for(Product p : productsManager.getAllProducts()){
            dtm.addRow(
                    new String[]{
                        String.valueOf(p.Id),
                        p.Name,
                        String.valueOf(p.Amount),
                        String.valueOf(p.Price),
                        String.valueOf(p.ProductGroupId),
                        String.valueOf(p.CurrencyId),
                        String.valueOf(p.ProductUnitId)
                    }
            );
        }
        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAccountAdd = new javax.swing.JButton();
        jButtonCurrencyAdd = new javax.swing.JButton();
        jButtonDestinationAdd = new javax.swing.JButton();
        jButtonDocumentAdd = new javax.swing.JButton();
        jButtonEmployeeAdd = new javax.swing.JButton();
        jButtonOperationAdd = new javax.swing.JButton();
        jButtonProductAdd = new javax.swing.JButton();
        jButtonProductGroupAdd = new javax.swing.JButton();
        jButtonProductUnitAdd = new javax.swing.JButton();
        jButtonTransactionAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonAccountAdd.setText("счет");
        jButtonAccountAdd.setFocusable(false);
        jButtonAccountAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAccountAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonAccountAdd);

        jButtonCurrencyAdd.setText("валюта");
        jButtonCurrencyAdd.setFocusable(false);
        jButtonCurrencyAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCurrencyAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonCurrencyAdd);

        jButtonDestinationAdd.setText("место");
        jButtonDestinationAdd.setFocusable(false);
        jButtonDestinationAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDestinationAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonDestinationAdd);

        jButtonDocumentAdd.setText("документ");
        jButtonDocumentAdd.setFocusable(false);
        jButtonDocumentAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDocumentAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonDocumentAdd);

        jButtonEmployeeAdd.setText("сотрудник");
        jButtonEmployeeAdd.setFocusable(false);
        jButtonEmployeeAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEmployeeAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonEmployeeAdd);

        jButtonOperationAdd.setText("операция");
        jButtonOperationAdd.setFocusable(false);
        jButtonOperationAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOperationAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonOperationAdd);

        jButtonProductAdd.setText("продукт");
        jButtonProductAdd.setFocusable(false);
        jButtonProductAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProductAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonProductAdd);

        jButtonProductGroupAdd.setText("прод.гр.");
        jButtonProductGroupAdd.setFocusable(false);
        jButtonProductGroupAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProductGroupAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonProductGroupAdd);

        jButtonProductUnitAdd.setText("ед.изм");
        jButtonProductUnitAdd.setFocusable(false);
        jButtonProductUnitAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProductUnitAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonProductUnitAdd);

        jButtonTransactionAdd.setText("транзакция");
        jButtonTransactionAdd.setFocusable(false);
        jButtonTransactionAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTransactionAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonTransactionAdd);

        jTable1.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccountAdd;
    private javax.swing.JButton jButtonCurrencyAdd;
    private javax.swing.JButton jButtonDestinationAdd;
    private javax.swing.JButton jButtonDocumentAdd;
    private javax.swing.JButton jButtonEmployeeAdd;
    private javax.swing.JButton jButtonOperationAdd;
    private javax.swing.JButton jButtonProductAdd;
    private javax.swing.JButton jButtonProductGroupAdd;
    private javax.swing.JButton jButtonProductUnitAdd;
    private javax.swing.JButton jButtonTransactionAdd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
